name: ChestFiller
version: '${project.version}'
main: com.levelatics.chestfiller.ChestFiller
api-version: 1.20
authors: [ LaurinRiess ]
description: Fill Chests with custom Loot Tables
commands:
  chestfill:
    description: Receive the Chest Filler Stick
    usage: /chestfill
